# -*- coding: utf-8 -*-
"""Aishwarya Sumbre-Task 5 -To explore Buisness Analytics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QkjWQdA5EOP7u0g1KMivGB509YwZnm7X

# **Importing library and Reading** **Dataset**
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()
import io
df2 = pd.read_csv(io.BytesIO(uploaded['SampleSuperstore.csv']))

import io
data = pd.read_csv(io.BytesIO(uploaded['SampleSuperstore.csv']))
# Print out `data`
data.info()

"""# **Displaying first 3 rows & checking shape of the data**"""

# Inspecting the first 3 rows
data.head(3)

data.shape

"""# **Checking and Correcting Datatypes**"""

data.info()  #gives information of all variables(columns)

#correcting the datatypes
data['Postal Code'] = data['Postal Code'].astype('object')
data['Quantity'] = data['Quantity'].astype('float64')

data.info()

"""# **To check and delete invalid values**"""

data.isnull() #to check if not we have any invalids values in the dataset.

data.dropna(inplace=True)  #to remove the invalid records within our dataset.

"""# **Checking overall Sales & Profit of the company**"""

#Checking Total Sales & Profit of the company
Sales=sum(data["Sales"])
Profit=sum(data["Profit"])

print("Overall Sales of the company is ", Sales, "dollors")
print("Overall Profits of the company is ", Profit, "dollors")

"""# **Overall Sales of the company is 2297200.860299955 dollors.**
# **Overall Profits of the company is 286397.02170000126 dollors.**

# **Creating new variables(columns) in the data.**
"""

data['Revenue'] = data['Sales'] - data['Profit']   # creating Revenue Column
data['GrossPrice'] = (data['Revenue'] - data['Profit']) / data['Quantity']  #creating gross price column
data['NetPrice'] = data['GrossPrice'] - (data['GrossPrice'] * data['Discount'])  #creating netprice column
data = data.drop(columns=['GrossPrice']) #deleting grossprice column , since it was only use to create netprice column
data.head(3)

"""# **Data visualization**"""

# Commented out IPython magic to ensure Python compatibility.
# Importing visualization libraries
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

"""#**Categorical data**"""

plt.figure(figsize=(8,7));sns.set_style('darkgrid')
sns.countplot(x="Ship Mode",data=data, palette='rainbow')

plt.figure(figsize=(8,7));sns.set_style('darkgrid')
sns.countplot(x='Segment',data=data, palette='rainbow')

plt.figure(figsize=(15,10)); sns.set_style('darkgrid');
sns.countplot(y='State',data=data, palette='rainbow')

plt.figure(figsize=(8,7));sns.set_style('darkgrid')
sns.countplot(x='Region',data=data, palette='rainbow')

plt.figure(figsize=(8,7));sns.set_style('darkgrid')
sns.countplot(x='Category',data=data, palette='rainbow')

plt.figure(figsize=(15,10));sns.set_style('darkgrid')
sns.countplot(y='Sub-Category',data=data, palette='rainbow')

plt.figure(figsize=(15,10))
sns.set_style('darkgrid')
sns.countplot(x='Region',hue="Ship Mode",data=data, palette='rainbow')

plt.figure(figsize=(20,10))
sns.catplot(x="Ship Mode", hue="Segment", col="Category",
                data=data, kind="count",
                height=8, aspect=.7);

"""#**we can see that for any category, Standard class shiping mode is highest with consumer segment**"""

plt.figure(figsize=(20,10))
sns.catplot(x="Ship Mode", hue="Region", col="Category",
                data=data, kind="count",
                height=8, aspect=.7)

"""#**We can see that for any category, Standard class shiping mode is highest with western region**

#**Continuous variable**
"""

df_Continuous = data.select_dtypes(include = ['float64', 'int64']) 
#To make histograms of continuous variables to see their data distributions
sns.set_style('darkgrid')
df_Continuous.hist(figsize=(15,15),xlabelsize=13, ylabelsize=13);

plt.figure(figsize=(15,5));
sns.barplot(x="Ship Mode", y="Profit", hue="Segment", data=data);plt.title('Ship Mode wise Profit through Segment',fontsize = 13)
plt.figure(figsize=(15,5));
sns.barplot(x="Ship Mode", y="Sales", hue="Segment", data=data);plt.title('Ship Mode wise Sales through Segment',fontsize = 13)
plt.show()

"""#**1.Profit are lowest on same day shipping mode for corporate segment.**
#**2.Sales are highest on same day shipping mode for corporate segment**
"""

plt.figure(figsize=(15,5));
sns.barplot(x="Ship Mode", y="Profit", hue="Region", data=data);plt.title('Ship Mode wise Profit through Region',fontsize = 13)
plt.figure(figsize=(15,5));
sns.barplot(x="Ship Mode", y="Sales", hue="Region", data=data);plt.title('Ship Mode wise Sales through Region',fontsize = 13)
plt.show()

plt.figure(figsize=(15,5));
sns.barplot(x="Ship Mode", y="Profit", hue="Category", data=data);plt.title('Ship Mode wise Profit through Category',fontsize = 13)
plt.figure(figsize=(15,5));
sns.barplot(x="Ship Mode", y="Sales", hue="Category", data=data);plt.title('Ship Mode wise Sales through Category',fontsize = 13)
plt.show()

plt.figure(figsize=(15,5));
sns.barplot(x="Segment", y="Profit", hue="Region", data=data);plt.title('Segment wise Profit through Region',fontsize = 13)
plt.figure(figsize=(15,5));
sns.barplot(x="Segment", y="Sales", hue="Region", data=data);plt.title('Segment wise Sales through Region',fontsize = 13)
plt.show()

plt.figure(figsize=(15,5));
sns.barplot(x="Segment", y="Profit", hue="Category", data=data);plt.title('Segment wise Profit through Category',fontsize = 13)
plt.figure(figsize=(15,5));
sns.barplot(x="Segment", y="Sales", hue="Category", data=data);plt.title('Segment wise Sales through Category',fontsize = 13)
plt.show()

"""#**Checking for Outliers**"""

#To detect the outlier in the data using the boxplot diagram
l=df_Continuous.columns
n=len(l)
number_of_figures_columnwise=3
number_of_figures_rowwise = (n-1)/number_of_figures_columnwise
plt.figure(figsize=(20,15))
for i in range(0,n):
    plt.subplot(number_of_figures_rowwise + 1,number_of_figures_columnwise,i+1)
    sns.set_style('darkgrid')
    sns.boxplot(data[l[i]],orient='v')
    plt.tight_layout()

"""#**Heatmap**"""

plt.figure(figsize=(15,15))
sns.set(style='whitegrid', font_scale=0.9)
corrs = data.corr()
mask = np.zeros_like(corrs)
mask[np.triu_indices_from(mask)] = True
sns.heatmap(corrs,annot=True)
plt.title('Correlation matrix')

"""**We can see there is negative correaltion between Discount & Profit so we can say that, as discount increases Company's profits are decreases.**


#**Grouping columns to get insights**
"""

data[['Sales','Profit', 'Discount']].groupby(['Sales'], as_index=False).mean().sort_values(by='Discount', ascending=False)

"""#**Pivot tables to get insights**"""

data.pivot_table(index=["Ship Mode"], values=["Sales","Profit","Discount","Quantity"], aggfunc =np.sum)

"""# **Lowest sales & profits are from same day ship mode.**"""

data.pivot_table(index=["Segment"], values=["Sales","Profit","Discount","Quantity"],  aggfunc =np.sum)

"""# **Lowest sales are from consumer segment & lowest profits are from Home office segment**"""

data.pivot_table(index=["Category"], values=["Sales","Profit","Discount","Quantity"],  aggfunc =np.sum)

"""# **Lowest sales are from office supplies category & lowest profits are from furniture category.**"""

data.pivot_table(index=["Sub-Category"],values=["Sales","Profit","Discount","Quantity"], aggfunc =np.sum)

pivot=data.pivot_table(index=["State"], values=["Sales","Profit","Discount","Quantity"],  aggfunc =np.sum)
x=pivot.sort_values('Sales', ascending=True)
x.head(5)

"""# **Top 5 States of Lowest sales of the company are North Dakota, West virginia, Maine, South Dakota, Wyoming.**"""

pivot=data.pivot_table(index=["State"], values=["Sales","Profit","Discount","Quantity"],  aggfunc =np.sum)
y=pivot.sort_values('Profit', ascending=True)
y.head(5)

"""# **Top 5 States of lowest Profits of the company are Texas, Ohio, Pennsylvania, lllinois, North Carolina.**

# **Insights**
(1) Overall Sales of the company is **22,97,201** dollors. Overall Profits of the company is **2,86,397** dollors.

(2)Profit are lowest & Sales are highest on same day shipping mode for **corporate **segment.

Profit are lowest on same day shiiping mode in **South region**.
Profit are lowest in Central region through **consumer segment**.
profit by Furniture is** lowest** in every shipping mode, Segment, Category.
Sales by **Office Supplies **is lowest in every shipping mode, Segment, Category.
sales are almost same for any shipping mode with segment.

(3)There is negative correaltion between Discount & Profit so we can say that, as discount increases Companny's profits are decreases

(4)There is negative correaltion between Discount & Profit so we can say that, as discount increases Companny's profits are decreases

(5)Top 5 States of Lowest sales of the company are North Dakota, West virginia, Maine, South Dakota, Wyoming.
Top 5 States of lowest Profits of the company are Texas, Ohio, Pennsylvania, lllinois, North Carolina.
"""